### ISSUE TITLE
Can not load loose file in /sound 

### ISSUE THREAD

**Issue by haohao698690** [JKAnderson/UXM#4]

**Comment by haohao698690** [comment]
It seems "patch' not work for /sound achieves, how to solve this problem? I made a female character voice mod for Elden Ring( outfits mod already works, thank you for your UXM tool) , but I could not let the game load them and I can’t repack the very large .bdt achieves such like Data0.bdt.

**Comment by Nordgaren** [comment]
Sound in Elden Ring doesn't work with UXM, as it's a different system.

Currently the only tool to do so is on ?ServerName?, the souls modding discord linked on Nexus.
