### ISSUE TITLE
Can not patch eldenring.exe after unpacking 1.03.1

### ISSUE THREAD

**Issue by NickEtlis** [JKAnderson/UXM#5]
![изображение_2022-03-20_123306_cut-photo ru](https://user-images.githubusercontent.com/101698524/159156447-3e9052bd-3c3c-449c-baf2-341f427c7ce2.png)

**Comment by Nimbasa1337** [comment]
Try right clicking on eldenring.exe, then click properties, uncheck the read only then click apply.

**Comment by NickEtlis** [comment]
> Try right clicking on eldenring.exe, then click properties, uncheck the read only then click apply.

It was not checked as read only

**Comment by Nordgaren** [comment]
> > Try right clicking on eldenring.exe, then click properties, uncheck the read only then click apply.
> 
> It was not checked as read only

you either need to run as admin or close your game.
