### ISSUE TITLE
Feature Request: Repacking of assets

### ISSUE THREAD

**Issue by moino157** [JKAnderson/UXM#6]
Hello,

I wanted to play Seamless Coop using Armor mods, but I can't launch the seamless_coop.exe using Mod Engine 2 so I have to unpack the game files and modify them manually. However, this increases loading times significantly. Could it be possible to have a feature that allows the repacking of game assets WITH modded parts (so not the Restore feature)?

**Comment by Nordgaren** [comment]
no

**Comment by Nordgaren** [comment]
use modengine
